# Generated by Django 2.1.7 on 2019-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(verbose_name='Date Added')),
                ('referrals', models.IntegerField(default=0)),
            ],
        ),
    ]
