# Generated by Django 2.1.7 on 2019-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0002_avenger_avenger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='avenger',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='avenger',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avenger',
            name='avenger_name',
            field=models.CharField(max_length=50),
        ),
    ]
