# Generated by Django 2.1.7 on 2019-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0003_auto_20190315_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenger',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
